### ISSUE TITLE
Marker File

### ISSUE THREAD

**Issue by wzhjlau2009** [cchauve/ANGeS#1]
@cchauve 
Hi，Thanks for the so powerful tools for construct ancestor genome！
I have a question about how to get the marker file from the instruction 1.01，are these markers is the synteny block from all the in-group spieces？ Thanks！

Best！

**Comment by cchauve** [comment]
Hello
The markers file can indeed be the synteny blocks of all the in-group and out-group species (if you have out-group species, you need markers for them too). You do not get them but as a user you have to provide them as an input to the program.
Regards
cedric chauve

**Comment by wzhjlau2009** [comment]
@cchauve 
Thanks very much for your help！
![image](https://user-images.githubusercontent.com/6326115/86190556-356c1700-bb77-11ea-919b-8e4b0e1c5f65.png)
I have check the example files in the software package，take this Poaceae for example， the files contains the information of synteny blocks for rice，Brachy，and Sorghum，and their chromosome ，first gene position and last gene position，right？And I want to know what the last column stands for ？how to get the whole block‘s orientation？Thanks！

Best！

**Comment by cchauve** [comment]
The last field is the strand orientation. Methods to construct synteny blocks generally provide this information.

**Comment by cchauve** [comment]
I do not see the markers file attached in your other email. Only the parameters file.
