### ISSUE TITLE
test example file failed

### ISSUE THREAD

**Issue by Bilinhu** [cchauve/ANGeS#3]
Hi, kind regards.
When I run the example, I got an error. Can you please help me ?

My command is
"python2 ~/software/ANGeS-master/src/MASTER/anges_CAR.py PARAMETERS_OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION"

I print the error out:
----> Started
----> Copying input
----> Filtering markers
----> Cleaning ACS file
----> Computing species
------> All species: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_SPECIES
----> Computing species pairs to compare
------> All informative pairs: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_PAIRS
----> Computing ancestral contiguous sets: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS
------> Species: Monodelphis_domestica Homo_sapiens
--------> Computing maximum common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_MCI_Monodelphis_domestica_Homo_sapiens
--------> Computing strong common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_SCI_Monodelphis_domestica_Homo_sapiens
--------> Computing all common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACI_Monodelphis_domestica_Homo_sapiens
------> Joining ACS files: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Monodelphis_domestica_Homo_sapiens, OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS
Traceback (most recent call last):
  File "/public/home/HuBiLin/software/ANGeS-master/src/ACS/ACS_join_files.py", line 62, in <module>
    in_matrices[m-st].from_file(sys.argv[m])
  File "/public/home/HuBiLin/software/ANGeS-master/src/COMMON/bm.py", line 196, in from_file
    f = open(file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Monodelphis_domestica_Homo_sapiens'

------> Species: Monodelphis_domestica Pan_troglodytes
--------> Computing maximum common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_MCI_Monodelphis_domestica_Pan_troglodytes
--------> Computing strong common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_SCI_Monodelphis_domestica_Pan_troglodytes
--------> Computing all common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACI_Monodelphis_domestica_Pan_troglodytes
------> Joining ACS files: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Monodelphis_domestica_Pan_troglodytes, OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS
Traceback (most recent call last):
  File "/public/home/HuBiLin/software/ANGeS-master/src/ACS/ACS_join_files.py", line 62, in <module>
    in_matrices[m-st].from_file(sys.argv[m])
  File "/public/home/HuBiLin/software/ANGeS-master/src/COMMON/bm.py", line 196, in from_file
    f = open(file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Monodelphis_domestica_Pan_troglodytes'

...
...
...

------> Species: Rattus_norvegicus Bos_taurus
--------> Computing maximum common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_MCI_Rattus_norvegicus_Bos_taurus
--------> Computing strong common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_SCI_Rattus_norvegicus_Bos_taurus
--------> Computing all common intervals: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACI_Rattus_norvegicus_Bos_taurus
------> Joining ACS files: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Rattus_norvegicus_Bos_taurus, OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS
Traceback (most recent call last):
  File "/public/home/HuBiLin/software/ANGeS-master/src/ACS/ACS_join_files.py", line 62, in <module>
    in_matrices[m-st].from_file(sys.argv[m])
  File "/public/home/HuBiLin/software/ANGeS-master/src/COMMON/bm.py", line 196, in from_file
    f = open(file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/ACS/BOREOEUTHERIAN_ACS_Rattus_norvegicus_Bos_taurus'

----> Weighting ACS: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/WEIGHT/BOREOEUTHERIAN_WACS
----> Creating PQR-tree: OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/CARS/BOREOEUTHERIAN_PQRTREE
----> Done

**Comment by cchauve** [comment]
Hello
I am sorry but I was not able to reproduce the error. I ran the same example than you using python 2.7.14, within a virtual environment where I had installed numpy, and it ran with no error. The error is that the ACS files do not seem to have been written. Could you check the content and writing rights of the directory OUANGRAOUA_ET_AL_2011_BOREOEUTHERIAN_SERIATION/?
cedric chauve

**Comment by Bilinhu** [comment]
Thanks a lot. 
We found the cause of the error.
Althongh I used python2,  the system used python3. 
To sovle it, I create a new conda env with python2.
