### ISSUE TITLE
syntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by wwenc** [cchauve/ANGeS#4]
[log.txt](https://github.com/cchauve/ANGeS/files/14457047/log.txt)
I meet some problem when I run the program data

**Comment by cchauve** [comment]
You re probably running ANGeS using python3. ANGeS has been written in python 2.7.

**Comment by wwenc** [comment]
But I using python2 to run the program.

**Comment by cchauve** [comment]
Then I do not see. The python error message indicates a python version issue.

**Comment by wwenc** [comment]
The python version I use is python 2.7.18,  but I can't run the code using the example data.
![截图 2024-03-20 19-17-59](https://github.com/cchauve/ANGeS/assets/152481196/73cae57b-60f1-4179-b90f-2aed15bd64b8)

**Comment by cchauve** [comment]
I am sorry but I do not see the problem. I ran the exact same experiment with no problem.

[ANGeS_log_BURKHOLDERIA_2.txt](https://github.com/cchauve/ANGeS/files/14668922/ANGeS_log_BURKHOLDERIA_2.txt)
